"""add product_name to cart

Revision ID: d5b4d6d3d7ca
Revises: 3e6c682cb1be
Create Date: 2026-05-10 16:18:49.012959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b4d6d3d7ca'
down_revision: Union[str, Sequence[str], None] = '3e6c682cb1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_name')
    # ### end Alembic commands ###
